### ISSUE TITLE
Slow startup Mac and Linux

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/AMO-Tools-Desktop#3262]
When run from command line, am seeing Exception:

Unhandled rejection TypeError: Cannot read property 'info' of null
    at autoUpdater.checkForUpdates.then (/Applications/MEASUR.app/Contents/Resources/app.asar/main.js:51:85)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at EventEmitter.ipcMain.on (/Applications/MEASUR.app/Contents/Resources/app.asar/main.js:49:37)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/MEASUR.app/Contents/Resources/electron.asar/browser/api/web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)

**Comment by rmroot** [comment]
Idk about the above error but production builds have been fixed with package updates and code cleanup. Will fix slow startup times. Tested on mac. Need to test linux

**Comment by rmroot** [comment]
Verified that production builds for linux and mac will work after angular upgrades.

use command `npm run ng-high-memory`
