### ISSUE TITLE
Problem with Auto Updater on Mac & Linux

### ISSUE THREAD

**Issue by DmitryHoward** [ORNL-AMO/AMO-Tools-Desktop#3264]
Causing very slow start up times on mac and linux. Auto update error seems to be the cause.

From Xubuntu build when running MEASUR from command line:

`Unhandled rejection Error: ENOENT: no such file or directory, open '/opt/MEASUR/resources/app-update.yml'
    at /opt/MEASUR/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/MEASUR/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:456:33)
    at Lazy.AppUpdater.configOnDisk (/opt/MEASUR/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:142:43)
    at Lazy.get value [as value] (/opt/MEASUR/resources/app.asar/node_modules/lazy-val/src/main.ts:18:25)
    at /opt/MEASUR/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/opt/MEASUR/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /opt/MEASUR/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/MEASUR/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/opt/MEASUR/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at EventEmitter.ipcMain.on (/opt/MEASUR/resources/app.asar/main.js:49:19)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/opt/MEASUR/resources/electron.asar/browser/api/web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)`

**Comment by gaccawi** [comment]
https://www.npmjs.com/package/electron-updater

https://github.com/iffy/electron-updater-example

So, looks like yes, there is support for Linux updates using AppImage
Also, yes, the Mac will continue to fail until I can create a build with the appropriate cert with verified publisher status.
