### ISSUE TITLE
WASM error on new version deploy

### ISSUE THREAD

**Issue by nbintertech** [ORNL-AMO/AMO-Tools-Desktop#6992]
Below WASM error encountered when new version deployed. Had to hard refresh to resolve. This should have been handled by the service worker hash checking implemented 2 releases ago

- Check if stale or conflicted bundle present from the first failed deploy of 1.5.2 causing issues
- Check suite 1.0.6 if new version of wasm or emsdk, client changes since last release
- No changes to MEASUR'S wasm instantiation since last release

async isntantiation was tested plenty re: #6706 #6734

>wasm streaming compile failed: LinkError: WebAssembly.instantiate(): Import #72 "env" "invoke_iid": function import >requires a callable
> 
> falling back to ArrayBuffer instantiation
> 
> failed to asynchronously prepare wasm: LinkError: WebAssembly.instantiate(): Import #72 "env" "invoke_iid": function import requires a callable
> 
> Aborted(LinkError: WebAssembly.instantiate(): Import #72 "env" "invoke_iid": function import requires a callable)
> 
> Unhandled Promise rejection: Aborted(LinkError: WebAssembly.instantiate(): Import #72 "env" "invoke_iid": function import requires a callable) ; Zone: <root> ; Task: Promise.then ; Value: RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #72 "env" "invoke_iid": function import requires a callable)
>     at abort (client.js:1:12607)
>     at client.js:1:14780
>     at tt.invoke (polyfills.b2f3fd755bff6dac.js:1:8551)
>     at tt.run (polyfills.b2f3fd755bff6dac.js:1:3499)
>     at polyfills.b2f3fd755bff6dac.js:1:19678
>     at tt.invokeTask (polyfills.b2f3fd755bff6dac.js:1:9243)
>     at tt.runTask (polyfills.b2f3fd755bff6dac.js:1:4187)
>     at Dt (polyfills.b2f3fd755bff6dac.js:1:11695) RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #72 "env" "invoke_iid": function import requires a callable)
>     at abort (https://measur.ornl.gov/client.js:1:12607)
>     at https://measur.ornl.gov/client.js:1:14780
>     at tt.invoke (https://measur.ornl.gov/polyfills.b2f3fd755bff6dac.js:1:8551)
>     at tt.run (https://measur.ornl.gov/polyfills.b2f3fd755bff6dac.js:1:3499)
>     at https://measur.ornl.gov/polyfills.b2f3fd755bff6dac.js:1:19678
>     at tt.invokeTask (https://measur.ornl.gov/polyfills.b2f3fd755bff6dac.js:1:9243)
>     at tt.runTask (https://measur.ornl.gov/polyfills.b2f3fd755bff6dac.js:1:4187)
>     at Dt (https://measur.ornl.gov/polyfills.b2f3fd755bff6dac.js:1:11695)

**Comment by nbintertech** [comment]
<img width="518" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXVvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8596a1203b7e393be4d9c319dba6025854bcf275/image%20%2867%29.png" alt="image (67).png" />

**Comment by nbintertech** [comment]
This error is a goose chase. Testing on dev server suggests that this problem won't occur with subsequent releases. Hanging up for now. Mark has my notes

**Comment by nbintertech** [comment]
Closing - 1.5.3 deployed flawlessly
